import ctypes
import os
import subprocess

try:
    SPI_SETDESKWALLPAPER = 20 
    img_path = "C:\\Users\\retro\\Desktop\\Clyon\\image.jpg"
    ctypes.windll.user32.SystemParametersInfoW(SPI_SETDESKWALLPAPER, 0,"image.jpg", 0)
except:
    print("man that's fxked up")

os.system('cmd /c "@echo off "')
os.system('cmd /c "echo ^<html^>^<head^>^<title^>BSOD^</title^> > bsod.hta "')
os.system('cmd /c "echo. >> bsod.hta "')
os.system('cmd /c "echo ^<hta:application id="oBVC" >> bsod.hta "')
os.system('cmd /c "echo applicationname="BSOD" >> bsod.hta "')
os.system('cmd /c "echo version="1.0" >> bsod.hta "')
os.system('cmd /c "echo maximizebutton="no" >> bsod.hta "')
os.system('cmd /c "echo minimizebutton="no" >> bsod.hta "')
os.system('cmd /c "echo sysmenu="no" >> bsod.hta "')
os.system('cmd /c "echo Caption="no" >> bsod.hta "')
os.system('cmd /c "echo windowstate="maximize"/^> >> bsod.hta "')
os.system('cmd /c "echo. >> bsod.hta "')
os.system('cmd /c "echo ^</head^>^<body bgcolor="red" scroll="no"^> >> bsod.hta "')
os.system('cmd /c "echo ^<font face="Lucida Console" size="4" color="#FFFFFF"^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.You computer has been infected by C`LyOn.^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.^</p^> >> bsod.hta "')
os.system('cmd /c "echo. >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.All your data been encrypted.^</p^> >> bsod.hta "')
os.system('cmd /c "echo. >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.To recover them, please send your mom to 1600 pennsylvania avenue nw washington dc 20500 using UPS.^</p^> >> bsod.hta "')
os.system('cmd /c "echo. >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.If data cant be recovered, you been fxcked real hard lol.^</p^> >> bsod.hta "')
os.system('cmd /c "echo. >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^> ^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.For Technical information:^</p^> >> bsod.hta "')
os.system('cmd /c "echo. >> bsod.hta "')
os.system('cmd /c "echo ^<p^> ^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.Contact your system administrator or technical support group for further assistance.^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.`.oooooo.```````````ooooo``````````````````````.oooooo.````````````````^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.d8P````Y8b```````````888``````````````````````d8P````Y8b```````````````^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>888```````````````````888`````````oooo````ooo`888``````888`ooo.`.oo.````^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>888```````````````````888```````````88.``.8```888``````888``888P"Y88b```^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>888``````````8888888``888````````````88..8````888``````888``888```888```^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>`88b````ooo```````````888```````o`````888``````88b````d88```888```888```^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.`Y8bood8P```````````o888ooooood8`````.8````````Y8bood8P```o888o o888o``^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.`````````````````````````````````.o..P`````````````````````````````````^</p^> >> bsod.hta "')
os.system('cmd /c "echo ^<p^>.``````````````````````````````````Y8P``````````````````````````````````^</p^> >> bsod.hta "')
os.system('cmd /c "echo. >> bsod.hta "')
os.system('cmd /c "echo ^</font^> >> bsod.hta "')
os.system('cmd /c "echo ^</body^>^</html^> >> bsod.hta "')
os.system('cmd /c "start "" /wait "bsod.hta" "')
os.system('cmd /c "del /s /f /q "bsod.hta" > nul "')
